services:
  - type: web
    name: notion-transfer-bot
    env: docker
    region: frankfurt
    plan: free
    scaling:
      minInstances: 0
      maxInstances: 1
    healthCheckPath: /health
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 7343545514:AAFUY4a9arc5dR2wHQU5uma3AC58HJ03vJM
      - key: WEBHOOK_URL
        value: https://notion-transfer-bot.onrender.com/webhook
    buildCommand: docker build -t notion-transfer-bot .
    startCommand: docker run notion-transfer-bot 